baseURL = "http://zyzyx.github.io/"
languageCode = "en-us"
title = "Jay Greguske's Website"
theme = "notepadium"
enableRobotsTXT = true

[params]
style = "dark"

[params.comments]
enable = false

[[params.nav.custom]]
title = "About"
url = "/about"

[[params.nav.custom]]
title = "Blog"
url = "/blog"
